const encounterTables = {
    ruins: [
      { encounter: "A mutated cave brute explodes through a crumbling wall" },
      { encounter: "A silent gelatinous cube sweeps up a corridor" },
      { encounter: "A roving owlbear scavenges for dead bodies to eat" },
      { encounter: "Rival crawlers confront the PCs; they were 'here first'" },
      { encounter: "1d6 rust monsters swarm a crack bubbling with mercury" },
      { encounter: "A legless suit of animated armor pulls itself along the floor" },
      { encounter: "A groaning wall collapses at the slightest touch" },
      { encounter: "A chalk note on the wall: 'Karov, we'll be at the Loyal Hog'" },
      { encounter: "Mort the goblin is digging in cracks for grubs and beetles" },
      { encounter: "The floor collapses into a pit 1d6 x 10 feet deep" },
      { encounter: "A raiding team of 2d4 hobgoblins moves in tight formation" },
      { encounter: "2d4 web-covered skeletons form from scattered bones" },
      { encounter: "1d4 giant dung beetles roll huge balls of dried excrement" },
      { encounter: "An ochre jelly hides inside a pond or sinkhole" },
      { encounter: "A single, perfect rose grows up between the flagstones" },
      { encounter: "2d4 bandits shutter lanterns and set up a hasty ambush" },
      { encounter: "Three goblins toughen each other's skulls with frying pans" },
      { encounter: "2d6 beastmen pummel a giant centipede with rocks" },
      { encounter: "A gas leak causes all light sources to explode and go out" },
      { encounter: "A gelatinous cube full of handy items is stuck inside a pit" },
      { encounter: "A swarm of clattering, gold scarab beetles flies into sight" },
      { encounter: "A wounded NPC staggers up to the PCs and begs for help" },
      { encounter: "A rusty portcullis slams down, separating the PCs" },
      { encounter: "A strangler hides above a backpack stuffed with rocks" },
      { encounter: "A weeping ghost floats by, distracted by its own ranting" },
      { encounter: "2d4 kobolds sneak up behind the PCs for a surprise attack" },
      { encounter: "Ancient clay pots vibrate with hypnotizing resonance" },
      { encounter: "1d6 gricks shred dead giant rats and use the fur for nesting" },
      { encounter: "Rival crawlers escort a frail noble tourist on an 'adventure'" },
      { encounter: "3d4 goblin scavengers barter and trade for odd trinkets" },
      { encounter: "2d4 dwarven miners (soldiers) shore up a collapsing wall" },
      { encounter: "2d4 giant wasps build a huge, papery nest on the ceiling" },
      { encounter: "A dense cloud of sulfuric mist rises from a floor crack" },
      { encounter: "A swarm of spiders surges out of a gauzy egg sack" },
      { encounter: "An ogre named Lud scratches rude words into the wall" },
      { encounter: "1d6 goblins brawl with 2d4 kobolds over a grick carcass" },
      { encounter: "2d4 giant bats roost on the ceiling; light disturbs them" },
      { encounter: "An ettercap spins web cocoons around its still-living prey" },
      { encounter: "1d6 cultists hunt for humanoid bones for a nefarious ritual" },
      { encounter: "A dryad searches for her tree that bugbears chopped up" },
      { encounter: "A deep gnome plays haunting music on humming fungi" },
      { encounter: "2d6 kobolds work in a makeshift, volatile alchemy lab" },
      { encounter: "A stone golem endlessly stacks the same rocks into piles" },
      { encounter: "Two darkmantles circle each other in a duel of intimidation" },
      { encounter: "2d6 goblins carry their bugbear king on a rickety litter" },
      { encounter: "2d4 cave creepers swarm up the hallway" },
      { encounter: "A recent campfire still burns with glowing cinders" },
      { encounter: "A minotaur guides the Wandering Merchant on a path" },
      { encounter: "Roll two encounters and combine the results (reroll 98-99)" },
      { encounter: "The body of a dead crawler holds a random magic item" }
    ],
    caves: [
      { encounter: "An enraged pair of manticores protect their 1d4 cubs" },
      { encounter: "1d6 possessed mushroomfolk charge in a murderous rage" },
      { encounter: "2d4 deep gnomes are irritated at the unwanted intrusion" },
      { encounter: "A band of 2d6 gnolls demands a toll of blood or gold" },
      { encounter: "A hungry, giant frog leaps out to swallow a PC" },
      { encounter: "1d6 ghouls stalk the living from the edge of the light" },
      { encounter: "Dripping water from above is actually searing acid" },
      { encounter: "A basilisk guards its nest of 1d4 stone eggs" },
      { encounter: "2d6 cannibalistic beastmen hunt for their next meal" },
      { encounter: "Cracked stalagmites vent superheated gouts of steam" },
      { encounter: "2d4 bugbears search for weaker creatures to rob" },
      { encounter: "2d6 orcs scavenge for food for their rotund hill giant queen" },
      { encounter: "2d4 dwarf knights bring news of calamity to the surface" },
      { encounter: "A scouting party of 2d4 drow creep through the caves" },
      { encounter: "An old chimera makes its nest among a pile of bones" },
      { encounter: "1d4 cave creepers cling to the walls of a new, deep rift" },
      { encounter: "3d4 kobolds carry mushrooms back to their troll overlord" },
      { encounter: "1d6 far-ranging duergar emerge from a small tunnel" },
      { encounter: "Toxic spores puff up from thousands of delicate fungi" },
      { encounter: "1d4 sleeping cloakers hang from the walls" },
      { encounter: "1d6 giant spiders lurk on the ceiling, waiting to ambush" },
      { encounter: "A kobold caught by the tail in a bear trap begs for help" },
      { encounter: "1d6 darkmantles bob and spin around stalactites" },
      { encounter: "A wounded, outcast drider skitters along the ceiling" },
      { encounter: "A trapped water elemental whirls inside a shallow puddle" },
      { encounter: "1d6 ettercaps affix thin lines of webbing across a passage" },
      { encounter: "Sharp stalactites fall with even the slightest vibration" },
      { encounter: "2d6 drow pursue a weary group of 2d4 bugbear escapees" },
      { encounter: "A Blue Tusk clan goblin shaman and 2d8 goblins rampage" },
      { encounter: "2d12 unguarded grick eggs are glued to the walls" },
      { encounter: "An elf warrior tracks a wounded otyugh that fled inside" },
      { encounter: "2d6 violet fungi slowly tromp past in search of water" },
      { encounter: "Luminous cave paintings of running elk emit soft light" },
      { encounter: "A troll drags the dead body of a rival crawler by the leg" },
      { encounter: "A giant snake rests inside a series of tunnels in the walls" },
      { encounter: "1d6 kobolds clash with 1d6 goblins over a prize mushroom" },
      { encounter: "A group of rival crawlers flees a chittering swarm of spiders" },
      { encounter: "A stone carving of a dwarf magically speaks to passersby" },
      { encounter: "A wraith hovers over its own recently deceased body" },
      { encounter: "A snorting wyvern trundles up the hall dragging a deer" },
      { encounter: "Binkin and Bobbin, twin halflings, tumble into the room" },
      { encounter: "1d6 buzzing stingbats gust from a narrow cave chimney" },
      { encounter: "An ochre jelly rears up from a thin crack in the floor" },
      { encounter: "1d8 lizardfolk lure 1d6 giant centipedes from their nest" },
      { encounter: "A patrol of 2d4 dwarves roasts mutton around a campfire" },
      { encounter: "A swarm of startled bats whirls past toward the surface" },
      { encounter: "The floor shakes as a tunneling bulette roves through" },
      { encounter: "The Wandering Merchant spelunks by on a truffle hunt" },
      { encounter: "Roll two encounters and combine the results (reroll 98-99)" },
      { encounter: "An orc mystic (L) offers 2 random beneficial potions" }
    ],
    forest: [
      { encounter: "3d6 giant spiders fill this part of the forest with thick webs" },
      { encounter: "A scavenging owlbear snorts around in the overgrowth" },
      { encounter: "1d6 boars flee a hunting party of 2d4 territorial centaurs" },
      { encounter: "2d6 elves stealthily trail the PCs and prepare to ambush" },
      { encounter: "A panther drops down on the rearmost character" },
      { encounter: "2d6 giant wasps drone about in a heavy treetop nest" },
      { encounter: "An ancient, rotted tree snaps and falls toward the PCs" },
      { encounter: "A hungry otyugh hides in a pile of rotting vegetation" },
      { encounter: "2d4 smelly, hooting apes throw rocks from behind trees" },
      { encounter: "A snow of glowing pixie-dust causes intense drowsiness" },
      { encounter: "A giant snake coils in the mud of a dried-out riverbed" },
      { encounter: "1d4 snarling badgers burst out of their hidden den" },
      { encounter: "1d4 treants offer pleasantries and slowly amble through" },
      { encounter: "1d6 Wolf Fang goblins riding worgs tear through the trees" },
      { encounter: "A blood vine tries to strangle a wounded berserker" },
      { encounter: "2d4 elves guard a treetop outpost; the PCs are trespassing" },
      { encounter: "A weald hag is foraging with her 2 truffle-hunting boars" },
      { encounter: "1d6 faeries try to hog-tie the PCs with thread and needle" },
      { encounter: "2d20 bobbing violet fungi crawl across the forest floor" },
      { encounter: "2d6 rangy wolves snap at the PCs and retreat out of reach" },
      { encounter: "1d6 giant spiders scuttle along the tree boughs" },
      { encounter: "2d6 muddy kobolds leap out and demand a passing toll" },
      { encounter: "A mage in a dangling web cocoon thrashes and screams" },
      { encounter: "1d4 rusty bear traps spring out from beneath the leaf litter" },
      { encounter: "2d4 Blood of Ramlaat tribe orcs chop angrily at trees" },
      { encounter: "2d6 goblins and 2d6 kobolds spill out of a cave, fighting" },
      { encounter: "A catgut wire triggers a wide, falling net hidden above" },
      { encounter: "Two brown bears charge the PCs from opposite sides" },
      { encounter: "A centipede swarm writhes out of the muddy ground" },
      { encounter: "A dryad stares into a well surrounded by old stone walls" },
      { encounter: "A smug leprechaun taunts the PCs from a high branch" },
      { encounter: "A shambling mound crashes up the side of a small ravine" },
      { encounter: "A massive, half-buried stone head peeks from the earth" },
      { encounter: "2d6 orcs make camp and roast a yelping peasant on a spit" },
      { encounter: "A rabid, frothing dire wolf staggers into sight and growls" },
      { encounter: "1d4 giant frogs try to grab 1d6 stingbats with their tongues" },
      { encounter: "Hrugin the troll drags 1d4 injured, tied-up rival crawlers" },
      { encounter: "Crimson roses sprout around a weathered statue of Gede" },
      { encounter: "An ogre tries to uproot a sapling to use as a new club" },
      { encounter: "2d6 goblins dance around a mighty oak hung with charms" },
      { encounter: "2d4 ranging green knights emerge from the trees" },
      { encounter: "2d4 kobolds carry their bugbear king in a beer barrel litter" },
      { encounter: "1d4 cave creepers charge out of a cave reeking of sulfur" },
      { encounter: "An irritable forest dragon stumps lazily through the woods" },
      { encounter: "A camp of 2d20 berserkers is willing to trade for goods" },
      { encounter: "An abandoned, overgrown stone chapel offers safe shelter" },
      { encounter: "An orc chieftain gives a fiery speech to 2d12 cheering orcs" },
      { encounter: "The Wandering Merchant pops out of a rotten tree stump" },
      { encounter: "Roll two encounters and combine the results (reroll 98-99)" },
      { encounter: "A shimmering unicorn steps out into a beam of sunlight" }
    ],
    arctic: [
      { encounter: "An albino kraken twitches inside a glassy mountain of ice" },
      { encounter: "2d20 cannibalistic bandits led by a frost troll make camp" },
      { encounter: "A group of orcs and a snow ape battle over deer meat" },
      { encounter: "A murderous fur trader on the run tries to sell stolen pelts" },
      { encounter: "3d6 ice-rimed skeletons burst from the snow" },
      { encounter: "1d6 will-o'-wisps made of ice float around a frozen pond" },
      { encounter: "An unnatural glow emanates from a deep crevasse" },
      { encounter: "A blind, dying mammoth charges toward sounds" },
      { encounter: "A wyvern circles the skies looking for seals or deer" },
      { encounter: "A blizzard kicks up, 1d4 damage/round if unsheltered" },
      { encounter: "A group of 2d6 hobgoblins hunt with 1d4 winter wolves" },
      { encounter: "White-scaled harpies lurk amid snowy rock shelves" },
      { encounter: "The Ice Rat Tribe (3d6 goblins) sets traps, is willing to trade" },
      { encounter: "The skull of a sapphire-eyed lich glares from a pillar of ice" },
      { encounter: "Fire-hating treants pose as a grove of silent pine trees" },
      { encounter: "1d4 smilodons stalk a lone, injured mammoth" },
      { encounter: "Six hobgoblin sorcerers perform a ritual in a snowy henge" },
      { encounter: "Two remorhaz duel; the strangest pose held longest wins" },
      { encounter: "The temperature drops, 1d6 damage/round if unsheltered" },
      { encounter: "2d8 winter wolves trail at a distance, waiting for night" },
      { encounter: "The Waste Walker appears (LV 10 wight, icy greatsword)" },
      { encounter: "A starving human is trapped in an icy, natural pit" },
      { encounter: "Thin ice weakened by hot springs shifts and cracks" },
      { encounter: "A polar bear attacks anyone who approaches her 1d4 cubs" },
      { encounter: "Behind an icy waterfall, a frost dragon sleeps in a cave" },
      { encounter: "A broken-winged roc fights off 2d6 human trappers" },
      { encounter: "1d6 rusty bear traps lurk beneath undisturbed snow" },
      { encounter: "A frost giant drives a sled pulled by three polar bears" },
      { encounter: "2d6 frostbitten zombies in armor stagger across the snow" },
      { encounter: "2d4 elven trackers camp atop a shelf overlooking ice fields" },
      { encounter: "The Lumberjack (N ogre, giant greataxe) drags a log sled" },
      { encounter: "2d8 sun-dazzled duergar flee the Dwarf Lord's trackers" },
      { encounter: "A slowly sliding ziggurat of ice drifts along the horizon" },
      { encounter: "1d6 snow apes drag a slain moose toward their den" },
      { encounter: "1d6 giant spiders string frosty webs across a narrow ravine" },
      { encounter: "A remorhaz chases 1d6 halflings toward its nest of young" },
      { encounter: "A group of rival crawlers emerges from a snowy cave" },
      { encounter: "A field of glittering, white mushrooms hums resonantly" },
      { encounter: "Hermit Leedrin (reaver) chooses the PCs as his next prey" },
      { encounter: "1d6 ghouls hide inside the shattered hull of a sea galleon" },
      { encounter: "2d4 dwarves with two alpine mastiffs follow a trail" },
      { encounter: "A wide tunnel in the ice leads into a purple worm's mouth" },
      { encounter: "A field of 2d20 dwarf corpses are zombies that rise at night" },
      { encounter: "2d6 Red Tooth goblins use a baby owlbear as ambush bait" },
      { encounter: "A camp of 2d20 yak herders offers food and shelter" },
      { encounter: "Prismatic sun falling on the ice is a portal to the Fey realm" },
      { encounter: "A banished cubi devil trudges angrily through the snow" },
      { encounter: "The Wandering Merchant rides on a caribou pulling a sled" },
      { encounter: "Roll two encounters and combine the results (reroll 98-99)" },
      { encounter: "Steam rises from an oasis of sulfuric, regenerative springs" }
    ],
    artisanDistrict: [
      { encounter: "An execution is about to happen; it's a PC's family member" },
      { encounter: "An angry efreeti rises out of a tarnished, brass lamp" },
      { encounter: "An assassin drops from above, mistaking a PC as a mark" },
      { encounter: "A glassblower accuses a PC of breaking a priceless vase" },
      { encounter: "A group of 2d6 thugs rush the stocks to free their leader" },
      { encounter: "A fight breaks out between two groups of rival nobles" },
      { encounter: "An herbalist accidentally creates a toxic cloud of smoke" },
      { encounter: "Thieves' Guild goons pick pockets while posing as beggars" },
      { encounter: "1d6 bandits hold a vendor at knifepoint and demand coin" },
      { encounter: "Horses being shod break free and stampede in the street" },
      { encounter: "A cloaked figure defaces a shrine to Madeera and bolts" },
      { encounter: "An arrogant warrior on a warhorse tries to kick a PC aside" },
      { encounter: "Brightly dressed acrobats tumble by; a pick-pocket follows" },
      { encounter: "1d6 guards mistake a PC for Pliny the Swift, a criminal" },
      { encounter: "Gaunt, robed clergy offer 'cleansing' (forcible conversion)" },
      { encounter: "1d6 breathless guards chase a pack of 2d4 mangy mastiffs" },
      { encounter: "A merchant hands a PC a gold goblet and screams, 'thief!'" },
      { encounter: "A disoriented manticore crash-lands in a busy square" },
      { encounter: "A deep sinkhole falls open; a swift river rushes by far below" },
      { encounter: "1d6 thugs posing as guards demand the PCs pay a toll" },
      { encounter: "A woman falls down, writhing, and rises as a wererat" },
      { encounter: "An anvil being lifted by ropes plunges toward a bystander" },
      { encounter: "A blacksmith's red-hot hammer slips and flies toward a PC" },
      { encounter: "Three halflings in a long jacket sell 'tonic' (sewer water)" },
      { encounter: "An angry customer smashes around inside a pottery shop" },
      { encounter: "2d6 Bywater Barons (thugs) jump a jeweler locking up" },
      { encounter: "Dissidents tip a tall statue of the Overlord toward a crowd" },
      { encounter: "A passing man falls dead to a poison dart meant for a PC" },
      { encounter: "An old, drunk noble challenges a PC to a duel to the death" },
      { encounter: "An open square hosts a contest of insult-slinging bards" },
      { encounter: "A bald, spectacled man watches the PCs and takes notes" },
      { encounter: "A jumpy woman palms a PC a note: 'They're watching!'" },
      { encounter: "A shiny object (crocodile eye) glints inside a sewer grate" },
      { encounter: "Sneering onlookers throw tomatoes at a harried bard" },
      { encounter: "A woman in a cowled cloak pulls down wanted posters" },
      { encounter: "2d4 kobolds pop out of the sewers and raid a bakery" },
      { encounter: "Bounty Festival celebrants whip passers with bound reeds" },
      { encounter: "A bronze statue of Ord winks and points toward a tavern" },
      { encounter: "A street mime follows a PC, imitating their actions" },
      { encounter: "A beggar holds up a bowl; inside is a freshly severed finger" },
      { encounter: "A cobbler jigs out into the street in a pair of cursed boots" },
      { encounter: "A turkey roaster offers a free leg to the strongest wrestler" },
      { encounter: "A lone City Watch member tries to swipe a necklace" },
      { encounter: "A group of women chase a halfling carrying a pie" },
      { encounter: "A hushed voice calls to a PC from inside a dark well" },
      { encounter: "A ray of sun outlines a hidden door back in an empty alley" },
      { encounter: "Rival crawlers challenge the group to a drinking contest" },
      { encounter: "The Wandering Merchant appears with a potion for sale" },
      { encounter: "Roll two encounters and combine the results (reroll 98-99)" },
      { encounter: "An appraisal reveals a PC's weapon is actually magical" }
    ],
    castleDistrict: [
      { encounter: "2d20 guards surround the group, accusing a PC of murder" },
      { encounter: "Piercing horns sound an alarm inside the royal palace" },
      { encounter: "Prisoners on a chain revolt in unison against their escort" },
      { encounter: "A drunk noble swings an axe, yelling, 'Off with 'er head!'" },
      { encounter: "Screaming, robed bathers stampede out of the bathhouse" },
      { encounter: "A visiting noble's honor guard chases a gray street cat" },
      { encounter: "A mounted group of knights charges down the busy street" },
      { encounter: "A condemned prisoner's noose breaks; he scampers away" },
      { encounter: "A fledgling gladiator takes offense at the garb a PC wears" },
      { encounter: "Overhead, a crumbling gargoyle breaks loose and falls" },
      { encounter: "A lion tears free from handlers leading it to the coliseum" },
      { encounter: "A wild-eyed playwright calls a PC an 'unread cretin'" },
      { encounter: "Armed tax collectors stop each person to levy a war tax" },
      { encounter: "A venerable knight mistakes a PC for Targ the Betrayer" },
      { encounter: "Two holy orders of rival crusaders square off in the street" },
      { encounter: "A hooded man slips into a sewer grate near the theater" },
      { encounter: "An elephant dragging chains bursts from the coliseum" },
      { encounter: "Mercenaries push people aside ahead of a visiting prince" },
      { encounter: "The street crumbles, revealing a dry cistern full of tunnels" },
      { encounter: "The water from a fountain rises into a humanoid shape" },
      { encounter: "A gleaming knight parades a sickly captive to the garrison" },
      { encounter: "Robal Goodwin darts by hauling bags of stolen royal gold" },
      { encounter: "A 30' tall catapult in a military parade ignites in fast flames" },
      { encounter: "A PC spots a new wanted poster with their own face on it" },
      { encounter: "A golden horseshoe peeks from the gutter filth" },
      { encounter: "Two rival gladiators start a fist fight in a rollicking tavern" },
      { encounter: "A spooked horse crashes into fragile building construction" },
      { encounter: "A dripping sewer beast bursts from the bathhouse doors" },
      { encounter: "Drunk Sir Galvin gets thrown out of the Blue Mare again" },
      { encounter: "An explosion rocks the nearest City Watch garrison" },
      { encounter: "A foreign dignitary mistakes a PC for a horse groom" },
      { encounter: "Bleary-eyed dwarf miners tunnel up through the street" },
      { encounter: "Dungeon prisoners grab at ankles from the barred gutters" },
      { encounter: "Four figures throw their hoods off, revealing devil masks" },
      { encounter: "The lead actor on an open street stage falls dead mid-word" },
      { encounter: "Two rival bounty hunters fight to capture the same man" },
      { encounter: "The PCs spot a group of crawlers dressed exactly like them" },
      { encounter: "A sewer grate thumps and clangs loudly, then goes still" },
      { encounter: "A cowled figure subtly hands a scroll to a passing woman" },
      { encounter: "A crossbow bolt flies at the PCs from the rooftops" },
      { encounter: "The famed singer Branzolini insists he knows a character" },
      { encounter: "A strong gust blows a key out of a window flower box" },
      { encounter: "A brash guard falls to his knee before the disguised Duke" },
      { encounter: "Two nervous men rush by with an object tied in a sheet" },
      { encounter: "Smoke begins pouring from the theater's upper windows" },
      { encounter: "A magic sword appears in the hand of a gladiator statue" },
      { encounter: "The Overlord rides by with a heavily armed honor guard" },
      { encounter: "The Wandering Merchant scalps premium coliseum seats" },
      { encounter: "Roll two encounters and combine the results (reroll 98-99)" },
      { encounter: "A visiting Duchess invites the PCs to attend a royal ball" }
    ],
    deepTunnels: [
      { encounter: "The Ten-Eyed Oracle drifts into sight, chattering of doom" },
      { encounter: "1d4 brain eaters walk surrounded by 3d6 duergar captives" },
      { encounter: "An albino hydra stampedes in, lashed on by 2d4 drow" },
      { encounter: "A duergar calls for help; 2d4 more prepare to ambush" },
      { encounter: "2d6 drow led by a drow priestess hunt for new prisoners" },
      { encounter: "2d6 pale, giant spiders skitter out of the darkness" },
      { encounter: "Dripping ooze douses flames and sticks creatures in place" },
      { encounter: "2d6 beastmen thralls haul a troll to their aboleth overlord" },
      { encounter: "2d4 giant leeches slither along the walls like snakes" },
      { encounter: "Shimmering spores kick up underfoot; they cause lethargy" },
      { encounter: "2d8 mushroomfolk track 2d4 thieving deep gnomes" },
      { encounter: "1d6 cave creepers glue dead drow to the walls as egg hosts" },
      { encounter: "1d8 battered dwarf knights retreat toward the upper caves" },
      { encounter: "1d4 ropers spring to life amid a nest of stalagmites" },
      { encounter: "A moaning, mushroom-infested mummy staggers along" },
      { encounter: "The earth shakes; a purple worm arrives here in 1d4 rounds" },
      { encounter: "2d12 grim duergar (N) run a traveling mercantile caravan" },
      { encounter: "A strangler stalks the PCs and ambushes from the rear" },
      { encounter: "An earthquake causes a tunnel to collapse" },
      { encounter: "An ogre zombie mindlessly wanders toward sounds" },
      { encounter: "1d4 hell hounds leap out of a sudden magma rupture" },
      { encounter: "An injured human warrior lies unconscious on the ground" },
      { encounter: "A drow-made trap of poison darts and web snares triggers" },
      { encounter: "A blind, pale halfling tends a flock of 2d6 cockatrice" },
      { encounter: "2d6 giant bats dive from the ceiling toward warm prey" },
      { encounter: "Two tribes of beastmen battle over a cold, obsidian altar" },
      { encounter: "The floor gives way into a sinkhole 2d6 x 10 feet deep" },
      { encounter: "Two minotaurs stalk each other and anyone in the way" },
      { encounter: "A nest of 2d12 darkmantles swarms any loud noises" },
      { encounter: "2d20 quiet mushroomfolk build a colony of fungi homes" },
      { encounter: "A deep gnome druid tends to a patch of neon mushrooms" },
      { encounter: "1d4 brain eaters try to escape a pursuing purple worm" },
      { encounter: "Puffs of sour-smelling gas cause auditory hallucinations" },
      { encounter: "2d6 void spiders step through starry portals that snap shut" },
      { encounter: "2d4 cloakers feast greedily on a dead purple worm" },
      { encounter: "A cave brute grapples with 1d4 ravenous cave creepers" },
      { encounter: "A group of rival crawlers out of torches stumbles into sight" },
      { encounter: "Gravity suddenly reverses for 1d4 rounds" },
      { encounter: "A crazed drow priest leads a pack of 3d6 drow ghouls" },
      { encounter: "2d4 gibbering mouthers slurp up a tunnel, wailing loudly" },
      { encounter: "A human priest who has been lost 15 years offers healing" },
      { encounter: "Ancient, moldy skeletons fuse into a hissing bone naga" },
      { encounter: "A shadow rises out of a PC's shadow and attacks" },
      { encounter: "2d6 drow dart around the attacks of 3d6 albino lizardfolk" },
      { encounter: "2d6 coal-streaked dwarven miners tunnel through the wall" },
      { encounter: "2d20 zigzagging motes of light heal 1 HP each if caught" },
      { encounter: "A night hag rides by on the back of a clear giant scorpion" },
      { encounter: "The Wandering Merchant squeezes out of a narrow fissure" },
      { encounter: "Roll two encounters and combine the results (reroll 98-99)" },
      { encounter: "An ancient treasure chest holds a random magic item" }
    ],
    desert: [
      { encounter: "A purple worm bursts from the sand and towers overhead" },
      { encounter: "3d6 raiding bandits from the Hidden City ride into view" },
      { encounter: "2d4 salamanders creep up on a sunning giant snake" },
      { encounter: "An arrogant sphinx demands the answer to a riddle" },
      { encounter: "2d4 ankhegs tunnel out of the sand in an ambush" },
      { encounter: "A tribe of 2d20 berserkers ride camels through the dunes" },
      { encounter: "The wind kicks up a blinding sandstorm for 1d4 hours" },
      { encounter: "A swarm of scarabs erupts from a low dune" },
      { encounter: "3d6 kobolds and a kobold sorcerer scavenge for beetles" },
      { encounter: "A vast field of poisonous cacti sprouts in the sands" },
      { encounter: "2d6 camouflaged lizardfolk hide under a thin layer of sand" },
      { encounter: "A pack of 2d6 mangy, wild mastiffs pursues at a distance" },
      { encounter: "1d6 parched gladiators linked by chains stumble along" },
      { encounter: "A tarnished, brass lamp has 10% chance of an efreeti inside" },
      { encounter: "2d4 desert elves on horseback fend off 2d8 ankhegs" },
      { encounter: "A collapsing keep of sandstone bricks houses 2d4 lions" },
      { encounter: "2d4 skittering rust monsters pick at a field of metal scraps" },
      { encounter: "A half-buried cairn houses 1d4 sarcophagi with mummies" },
      { encounter: "1d4 bone-barbed nets snap up from beneath the sand" },
      { encounter: "1d6 shadows hide in the shade of jagged rock pillars" },
      { encounter: "2d4 salamanders drag two ankheg carcasses on litters" },
      { encounter: "A giant scorpion sneaks up behind a meditating goblin" },
      { encounter: "The false mirage of an oasis shimmers in the distance" },
      { encounter: "A bone naga slithers over the sand, leaving a curving trail" },
      { encounter: "1d4 manticores circle above a ring of dead lizardfolk" },
      { encounter: "An iron golem plunges resolutely through the sand drifts" },
      { encounter: "A towering sand dune shifts and collapses toward the PCs" },
      { encounter: "War horns sound in the distance; 3d20 bandits approach" },
      { encounter: "A fire elemental burns like a bonfire atop a tall dune" },
      { encounter: "2d6 peasants and merchants rest at a palm-ringed oasis" },
      { encounter: "A herd of 2d6 desert centaurs cautiously draw closer" },
      { encounter: "2d6 vultures pinwheel above the PCs, drawing attention" },
      { encounter: "A dry riverbed is embedded with massive nautiloid fossils" },
      { encounter: "1d4 cobras hide under an upturned woven basket" },
      { encounter: "A funnel of sand collapses in, revealing a giant spider den" },
      { encounter: "A tawny wolf limps into sight; 2d6 others creep up behind" },
      { encounter: "3d6 kobolds hurl rocks from small caves in a rocky ridge" },
      { encounter: "A sweeping rain begins, threatening floods in the lowlands" },
      { encounter: "A fire dragon passes overhead; it spots PCs in the open" },
      { encounter: "A djinni and efreeti trade blows in a thunderous duel" },
      { encounter: "Algariz the desert dragon (L) relaxes on a smoldering rock" },
      { encounter: "1d8 Steelsworn clan hobgoblins on hippogriffs fly on patrol" },
      { encounter: "An irritated mage digs around the top of a buried pyramid" },
      { encounter: "2d6 red-robed cultists battle with 2d4 bandits on camels" },
      { encounter: "A burning, reborn phoenix rises into the sky: +1 luck token" },
      { encounter: "The bleached skeleton of a ship covers a freshwater well" },
      { encounter: "A pair of bulettes burrow in a circle around a black pillar" },
      { encounter: "The Wandering Merchant rides a heavily laden camel" },
      { encounter: "Roll two encounters and combine the results (reroll 98-99)" },
      { encounter: "The legendary Alabaster Library of Gehemna materializes" }
    ],
    grasslands: [
      { encounter: "A roc passes overhead and then divebombs the PCs." },
      { encounter: "A hunting smilodon prowls through the tall grass." },
      { encounter: "A baby mammoth flees a pack of 2d6 wolves." },
      { encounter: "A pale wizard in black robes stands silently on a tall rock." },
      { encounter: "1d4 giant dung beetles roll manure toward a towering pile." },
      { encounter: "A whirling dust devil is actually an angry air elemental." },
      { encounter: "Dark, tall clouds roll in; a violent thunderstorm is imminent." },
      { encounter: "1d4 fierce griffons savagely tear apart a horse carcass." },
      { encounter: "3d6 kobolds pop out of prairie dog holes and fling rocks." },
      { encounter: "Smoke drifts on the wind; a growing wildfire rages nearby." },
      { encounter: "An earth elemental slurps around in a muddy geyser field." },
      { encounter: "1d4 wyverns sun themselves atop striated badlands hills." },
      { encounter: "2d6 rust-red velociraptors prowl the plains for slow prey." },
      { encounter: "Two hill giants trudge along with a horse under each arm." },
      { encounter: "A pack of 3d6 gnolls trails a rhino peppered with arrows." },
      { encounter: "An empty tower shell is covered in finger-painted runes." },
      { encounter: "The grass bends in an S shape; it's a roving giant snake." },
      { encounter: "A stampede of 2d6 mammoths thunders toward the PCs." },
      { encounter: "A lone orc sits inside a weathered henge of stones." },
      { encounter: "Rune-etched boulders seal off ancient burial cairns." },
      { encounter: "3d6 horse-riding berserkers crest over the horizon." },
      { encounter: "A wyvern swoops at a human backed up to a cliff edge." },
      { encounter: "Wedges on strings hold precarious boulders in place." },
      { encounter: "Two gnolls fight inside a ring of 2d4 chanting gnolls." },
      { encounter: "1d4 wild boars drink at a thin, winding stream." },
      { encounter: "2d6 bandits on horses drive a herd of bison toward a cliff." },
      { encounter: "Cursed wind flutes on poles hypnotize with their sound." },
      { encounter: "A bandit chieftain (x2 LV and damage) demands a duel." },
      { encounter: "2d4 lions watch intently from the banks of a river." },
      { encounter: "2d20 nervous peasants stare from their circle of yurts." },
      { encounter: "A druid in a wolf cloak paints red symbols on dead bison." },
      { encounter: "2d4 pegasi wheel overhead, teaching 2 clumsy foals to fly." },
      { encounter: "A grass-woven effigy of a horse stands in an empty field." },
      { encounter: "An ochre basilisk basks on a rock and puffs its neck pouch." },
      { encounter: "An albino chimera sails out of a white, fluffy cloud." },
      { encounter: "1d4 ankhegs hiss and spit at a rampaging bulette." },
      { encounter: "A rival crawling party rides in a howdah on an elephant." },
      { encounter: "A fossilized tree teeters on top of an eroding mud pillar." },
      { encounter: "A T-Rex gallops along after a herd of panicked antelope." },
      { encounter: "2d6 gnolls creep below the tall grass line, spears ready." },
      { encounter: "A mammoth gently pats heads with its trunk: +1 luck token." },
      { encounter: "A mated pair of smilodons leaps down from grassy ridges." },
      { encounter: "A stone golem made of glittering gypsum guards a field." },
      { encounter: "A shadow ripples over the grass like a dark stain." },
      { encounter: "2d12 berserker hunters welcome guests to their camp." },
      { encounter: "A bull-headed shrine to a lost god repels roving beasts." },
      { encounter: "A sun-blind cave brute wildly lurches toward sounds." },
      { encounter: "The Wandering Merchant flees from a furious rhino." },
      { encounter: "A principi angel strides from a storm cloud to gift a boon." }
    ],
    highDistrict: [
      { encounter: "The Overlord levies a 500 gp 'filth tax' on the PCs" },
      { encounter: "The Duke's son challenges a PC to a duel to the death" },
      { encounter: "The Overlord's Assassins leap out and demand explanation" },
      { encounter: "Crawlers with the Mercenaries' Guild confront the PCs" },
      { encounter: "A burglar disguised as a butler leads the PCs to an ambush" },
      { encounter: "Baron Clard's wife winks at a PC; he notices and is furious" },
      { encounter: "Three casks of fine wine break loose and careen at the PCs" },
      { encounter: "A noble's pet panther spooks and tears free of its leash" },
      { encounter: "A giant scorpion (a rare delicacy) escapes a fine restaurant" },
      { encounter: "An angrily thrown chamber pot flies down toward the PCs" },
      { encounter: "A drug-addled bard in a loincloth flails wildly at the PCs" },
      { encounter: "A bribed fortune-teller declares the PCs 'future criminals'" },
      { encounter: "A skeptical City Watch patrol follows the group around" },
      { encounter: "An immaculately clean child tries to trip a PC as they go by" },
      { encounter: "Three finely dressed thugs extort a banker for 'protection'" },
      { encounter: "Six thugs race from the Royal Jeweler with a fat bag in tow" },
      { encounter: "A bailiff and four guards assess the PCs for any owed taxes" },
      { encounter: "A gruff noble shoves past a PC, muttering 'lowborn scum'" },
      { encounter: "A malfunctioning magical ward casts web on the PCs" },
      { encounter: "An unconvincing cry for help comes from behind a tavern" },
      { encounter: "A vendor of fine silks accuses a PC of tearing a costly scarf" },
      { encounter: "Duchess Gorvalt swoons near the edge of a high balcony" },
      { encounter: "Masked revelers crowd the streets; a dagger flies at a PC" },
      { encounter: "Lord Larvin chokes on his wine; it's been poisoned" },
      { encounter: "The City Watch rousts gutter-sleepers; one is a known NPC" },
      { encounter: "A City Watch patrol searches the PCs for suspicious items" },
      { encounter: "A teenaged heckler insults the characters' clothing" },
      { encounter: "A cowled woman beckons the PCs into the rose garden" },
      { encounter: "A child with magical power accidentally summons an imp" },
      { encounter: "One of Miss Fralk's etiquette students slips off into an alley" },
      { encounter: "A noble asks a PC to punch him and gets upset either way" },
      { encounter: "The PCs find a note: 'Bring the poison to the Sapphire Sky'" },
      { encounter: "Through a dark window, the PCs spot 6 swaying ghouls" },
      { encounter: "A drunk socialite casually admits to killing her husband" },
      { encounter: "Rival crawlers brandish their new sheriff pins and writs" },
      { encounter: "1d6 City Watch are outclassed trying to catch an acrobat" },
      { encounter: "A PC recognizes a fraud posing as Sir Wyndos the Bold" },
      { encounter: "A brass monkey statue turns 1 cp into 1 gp 1% of the time" },
      { encounter: "A weeping bard playing tragic ballads follows the PCs" },
      { encounter: "The PCs commit a social gaffe against a visiting prince" },
      { encounter: "Jaunty old Sir Faust pulls a pearl out of a PC's ear as a gift" },
      { encounter: "A night hag posing as a baker hands out drugged tarts" },
      { encounter: "The PCs notice 1d4 well-preserved zombies blending in" },
      { encounter: "A political dissenter takes cover among the PCs and rants" },
      { encounter: "A Reverend Sister (acolyte) offers healing/blessing to a PC" },
      { encounter: "A formerly taxidermied basilisk charges out of a curio shop" },
      { encounter: "A real vampire stalks unnoticed among masqueraders" },
      { encounter: "The Wandering Merchant is selling loaded dice (5 gp)" },
      { encounter: "Roll two encounters and combine the results (reroll 98-99)" },
      { encounter: "The Overlord is dining and invites the PCs to the meal" }
    ],
    jungle: [
      { encounter: "Mossy, lifelike statues crop up; a medusa resides nearby" },
      { encounter: "A T-Rex thunders over the ground, looking for fresh meat" },
      { encounter: "3d6 hissing viperians encircle 2d4 red-scaled lizardfolk" },
      { encounter: "A kobold sorcerer riding a leashed crocodile demands gold" },
      { encounter: "A yowling panther falls onto a PC from a high tree branch" },
      { encounter: "A snorting gorilla prowls in the dense ground vegetation" },
      { encounter: "A patch of muddy ground is actually a pool of quicksand" },
      { encounter: "2d4 drow in basilisk hide armor creep through the mist" },
      { encounter: "1d4 giant scorpions scuttle down thick tree trunks" },
      { encounter: "A carpet of minuscule, biting ants pours across the ground" },
      { encounter: "2d4 stingbats flutter and dart through the dense canopy" },
      { encounter: "1d4 giant frogs peek their eyes out of a mossy, still pond" },
      { encounter: "2d6 Bloodspear tribe lizardfolk check net traps for game" },
      { encounter: "2d4 yellow-striped velociraptors circle around the PCs" },
      { encounter: "A howling gorilla punches and bites a thrashing crocodile" },
      { encounter: "2d6 drow in chitin armor flit among colossal, mossy pillars" },
      { encounter: "A forest dragon slumbers outside a vine-choked cave" },
      { encounter: "A slimy troll swings between tree branches like an ape" },
      { encounter: "Carnivorous, pink flowers unfurl and fling poisonous darts" },
      { encounter: "2d4 zombies (former crawlers) stagger through the jungle" },
      { encounter: "A towering brachiosaurus slowly plods through, grazing" },
      { encounter: "A flailing human arm juts out of a dark pool of quicksand" },
      { encounter: "Heady, perfumed flowers lull creatures into a deep sleep" },
      { encounter: "A giant zombie (x3 LV and damage) claws out of the earth" },
      { encounter: "1d6 pterodactyls roost in the trees around a deep sinkhole" },
      { encounter: "2d4 drow covered in white war paint charge out of a cave" },
      { encounter: "Flimsy reeds and grass cover a swarm of snakes in a 10' pit" },
      { encounter: "A drider clings to a tree, scanning the area with sharp eyes" },
      { encounter: "A viperian wizard and 1d4 zombie thralls inspect a boulder" },
      { encounter: "1d6 playful faeries cavort around a sun-dappled clearing" },
      { encounter: "Doctor Bartom Halsy leads an expedition of 2d12 peasants" },
      { encounter: "A giant snake coils on a low branch, forked tongue flicking" },
      { encounter: "1d4 spiders hang on threads at head-height" },
      { encounter: "2d4 giant centipedes wriggle out of a hollow, rotting log" },
      { encounter: "1d4 crocodiles mock charge out of a river with bared fangs" },
      { encounter: "Two adolescent forest dragons clash over a territory claim" },
      { encounter: "A frantic rival crawling party offers a gold idol to the PCs" },
      { encounter: "2d4 berserkers carry a baby basilisk in a wicker basket" },
      { encounter: "Javelins shoot from the mouth of a hulking stone statue" },
      { encounter: "1d4 berserkers and a druid hunt with their trained basilisk" },
      { encounter: "A wandering mushroomfolk mystic offers healing salves" },
      { encounter: "A naga guards a towering, stone ruin housing a black altar" },
      { encounter: "A viperian ophid leads 2d4 viperians on a patrol" },
      { encounter: "2d6 drow dart with silk thread around a bellowing cyclops" },
      { encounter: "2d20 Amber-Eye tribe lizardfolk bustle around mud huts" },
      { encounter: "A beam of sun touches the top of a three-stepped ziggurat" },
      { encounter: "A sphinx draped in jade and gold lounges on a stone dais" },
      { encounter: "The Wandering Merchant flees a group of 2d4 beastmen" },
      { encounter: "Roll two encounters and combine the results (reroll 98-99)" },
      { encounter: "A radiant couatl snakes through the air; it offers a blessing" }
    ],
    lowDistrict: [
      { encounter: "3d6 zombies lurch out of a smoke-belching charnel house" },
      { encounter: "A reaver and 4 bandits look for weaklings to shake down" },
      { encounter: "2d6 pirates and 2d4 merchants (guards) fight on the docks" },
      { encounter: "A grizzled sailor spits at the PCs and sneers, 'landlubbers'" },
      { encounter: "A half-orc is thrown through a tavern window into a PC" },
      { encounter: "1d6 shifty ruffians linger outside a butcher's shop" },
      { encounter: "A dyehouse dumps a boiling, toxic slurry into the street" },
      { encounter: "Children throw mud pies at sputtering men in the stocks" },
      { encounter: "A cloaked person sneaks between graveyard headstones" },
      { encounter: "A backed-up sewer grate geysers waste at passersby" },
      { encounter: "A man carts a thumping coffin toward the charnel house" },
      { encounter: "A woman whispers, 'play along' and chats as guards pass" },
      { encounter: "Drunk sailors hang off the PCs and clumsily pick pockets" },
      { encounter: "Masons unseal an old well, releasing 2d6 giant centipedes" },
      { encounter: "Rival gangs of 2d4 dirt-streaked children bite and scratch" },
      { encounter: "Four thugs loom over a woman who unlocks a warehouse" },
      { encounter: "A wheezing beggar offers portents in exchange for coin" },
      { encounter: "Thieves' Guild footpads tail the PCs from 20 paces back" },
      { encounter: "The shell of a burned warehouse collapses into a tenement" },
      { encounter: "2d4 kobolds rain stones down from a warehouse's eaves" },
      { encounter: "Workers cart a yowling, caged tiger away from the docks" },
      { encounter: "A young gravedigger slips and falls into a deep grave" },
      { encounter: "Hidden thieves pull ropes up in a side alley to trip marks" },
      { encounter: "A shop owner whispers about 'exotic goods' for sale" },
      { encounter: "1d6 Thieves' Guild toughs spoiling for a fight approach" },
      { encounter: "A brawl of 2d6 drunk commoners spills out of a tavern" },
      { encounter: "Clay shingles fall off the crumbling roof of a warehouse" },
      { encounter: "A smith flings still-hot horseshoes onto a pile near the PCs" },
      { encounter: "A blind old woman presents her 'cat' (a vicious giant rat)" },
      { encounter: "A troupe of jugglers swig ale and wildly flip daggers" },
      { encounter: "A mercenary on a horse drags a lank man to debtor's court" },
      { encounter: "Two beggars slap and scratch over a burned rat-on-a-stick" },
      { encounter: "A pure spring bubbles up between cracked cobblestones" },
      { encounter: "A feeble beggar turns out to be 3 kobolds in a burlap sack" },
      { encounter: "A bailiff and four guards haul a struggling man along" },
      { encounter: "Two rival dog fighters lose control of their mastiffs" },
      { encounter: "Rival crawlers accuse the PCs of looting in 'their territory'" },
      { encounter: "A kingdom of cats gathers beneath the docks or porches" },
      { encounter: "A wheedling torchbearer follows and begs for work" },
      { encounter: "A shrill scream erupts from a row of moldy storage sheds" },
      { encounter: "Lady Unwin asks the PCs directions to the seedy Red Rat" },
      { encounter: "Three thugs in hoods drag a large bag from a tenement" },
      { encounter: "A red-eyed being watches from a shadowed window" },
      { encounter: "2d6 Bywater Barons (thugs) mob a City Watch patrol" },
      { encounter: "A refinery discards a barrel of rancid blubber (10 oil vials)" },
      { encounter: "Old Esmerelda hands out cups of mulled wine (heals 1d4)" },
      { encounter: "A pox-marked beggar is actually the Duke in disguise" },
      { encounter: "The Wandering Merchant sells the deed to an old shop" },
      { encounter: "Roll two encounters and combine the results (reroll 98-99)" },
      { encounter: "A dropped magic item glitters inside a filthy gutter" }
    ],
    market: [
      { encounter: "Six chaos cultists throw burlap bags over the PCs' heads" },
      { encounter: "A drunk, wobbly knife-thrower hurls a blade toward a PC" },
      { encounter: "A runaway cart of lettuce heads crashes down the street" },
      { encounter: "A passing noble stumbles and blames it on a character" },
      { encounter: "Three scrawny children pluck at the PCs' gear and pockets" },
      { encounter: "A hooded hawk lashes out at a PC who passes too close" },
      { encounter: "An overladen dung pile collapses toward the group" },
      { encounter: "A glimpse into an alley reveals a few shadowy vendors" },
      { encounter: "The City Watch asks the PCs to 'distract' a vendor's guards" },
      { encounter: "A firebreather gouts flames, 25% chance of misfire" },
      { encounter: "A woman stealthily sprinkles powder into a spice barrel" },
      { encounter: "A herd of goats clogs traffic; the goats chew on loose gear" },
      { encounter: "A red-faced fruit vendor accuses a woman of theft" },
      { encounter: "A vendor cuts open a fruit that smells like decaying flesh" },
      { encounter: "Two sorcerers having a psychic contest start to cause fires" },
      { encounter: "Smashing pottery and yells echo from a covered wagon" },
      { encounter: "A famous sword master (gladiator) drinks alone in a tent" },
      { encounter: "2d4 bored caravan guards try to provoke trouble" },
      { encounter: "A spooked horse rears up, threatening to throw its rider" },
      { encounter: "A dart with a note lands at a PC's feet: 'meet at Liona's'" },
      { encounter: "Two shouting merchants brandish daggers at each other" },
      { encounter: "A tattoo artist offers a character a tattoo at half price (5 gp)" },
      { encounter: "A merchant under duress serves as bait for a cultist's trap" },
      { encounter: "A sword-swallower tries to use a PC's weapon for his show" },
      { encounter: "A visiting noble swaggers through with 6 pushy guards" },
      { encounter: "A small monkey in a vest and red cap steals people's gear" },
      { encounter: "A team of jugglers secretly picks onlookers' pockets" },
      { encounter: "A hulking berserker flips a table and starts a fist fight" },
      { encounter: "A man with a red-stained mouth offers addictive bloodroot" },
      { encounter: "A goblin runs by hauling four flapping chickens by the legs" },
      { encounter: "Four robed monks insist the PCs submit to an exorcism" },
      { encounter: "Rival crawlers toast around a still-bleeding troll head" },
      { encounter: "A chained brown bear tears loose and goes on a rampage" },
      { encounter: "A beggar offers to exchange a stolen signet ring for gold" },
      { encounter: "A crone in a smoky tent offers to curse enemies for a fee" },
      { encounter: "A street urchin steals a loaf of bread from a baker's stall" },
      { encounter: "The City Watch tries to arrest an outraged snake charmer" },
      { encounter: "A shining, red apple appears in a statue of Gede's hand" },
      { encounter: "1d6 'commoners' (guards) trail a lordling at a distance" },
      { encounter: "A hunched old woman whispers a portent while passing" },
      { encounter: "2d4 kobolds pop out of barrels and snatch at merchandise" },
      { encounter: "Religious mendicants place beads around the PCs' necks" },
      { encounter: "A burglar tries to plant a stolen ivory statuette on a PC" },
      { encounter: "A mossy centaur clops along, eliciting gasps; he seeks a PC" },
      { encounter: "Three angry camels begin spitting at anyone nearby" },
      { encounter: "An apothecary offers the PCs a sample of teas or tinctures" },
      { encounter: "An antique mirror shatters, releasing the wraith inside it" },
      { encounter: "The Wandering Merchant has a random scroll for sale" },
      { encounter: "Roll two encounters and combine the results (reroll 98-99)" },
      { encounter: "The disguised Overlord pushes a diamond into a PC's hand" }
    ],
    mountain: [
      { encounter: "A howling blizzard or thunderstorm bars travel for 1d4 days" },
      { encounter: "2d20 goblins led by a goat giant swarm over the cliffs" },
      { encounter: "An airborne manticore and wyvern ferociously clash" },
      { encounter: "Braaqul, hobgoblin spy, gathers intelligence on the PCs" },
      { encounter: "2d6 goblins fling rocks and flaming excrement at the PCs" },
      { encounter: "A group of 2d4 dwarf bandits hustle travelers for a toll" },
      { encounter: "A boulder breaks loose, causing an avalanche of rocks" },
      { encounter: "Skaldor the troll crunches on dwarf bones in his dank cave" },
      { encounter: "1d6 salamanders slither out of a misty, hot spring pool" },
      { encounter: "An earthquake shakes the peaks and unleashes landslides" },
      { encounter: "A screaming swarm of bats careens out of a narrow ravine" },
      { encounter: "3d6 hobgoblins march along a pass in tight formation" },
      { encounter: "1d4 pyromancers (mages) meditate beside a lava pool" },
      { encounter: "1d4 fire giants forge enormous weapons in a smoky cave" },
      { encounter: "1d6 goblins sneak along a ridge line toward 2d4 peasants" },
      { encounter: "3d6 orcs make camp in an empty, crumbling stone keep" },
      { encounter: "A frost giant trudges along a snowy ridge, singing loudly" },
      { encounter: "2d4 harpies cling to the sharp edges of steep cliff faces" },
      { encounter: "A volcanic eruption rains down ash, hot gas, and lava flow" },
      { encounter: "A tawny mountain lion leaps from hiding at the rear PC" },
      { encounter: "A reaver and 2d6 bandits try to capture the characters" },
      { encounter: "A peasant lies with a leg trapped beneath a fallen boulder" },
      { encounter: "A luring will-o'-wisp floats over a hidden, old mine shaft" },
      { encounter: "2d6 berserkers in mountain lion cloaks hunt for game" },
      { encounter: "An ettercap spins a funnel of webs over a narrow ravine" },
      { encounter: "2d4 beastmen close in a circle around 1d4 dwarf soldiers" },
      { encounter: "A stack of logs breaks free and tumbles down the slopes" },
      { encounter: "A nightmare soars out of the caldera of a nearby volcano" },
      { encounter: "2d4 apes hoot and roll rocks at creatures passing below" },
      { encounter: "A fire dragon sleeps on a hill of coins encircled by lava" },
      { encounter: "2d6 dwarf soldiers guard the vaulted doors to their halls" },
      { encounter: "A cyclops rips a tree from the ground to use as a club" },
      { encounter: "A massive profile of a dwarven king is carved into the cliffs" },
      { encounter: "2d6 salamanders bask on flat, sun-warmed rocks" },
      { encounter: "A bristling roc warily guards its nest of 1d4 gigantic eggs" },
      { encounter: "2d4 goblins pluck a live cockatrice to prepare it for cooking" },
      { encounter: "A group of rival crawlers stares in puzzlement at a map" },
      { encounter: "A rusty, dwarven axe is stuck in a bleached minotaur skull" },
      { encounter: "1d4 hobgoblins on griffons throw javelins at the PCs" },
      { encounter: "1d6 snarling hell hounds lunge out of a glowing cave" },
      { encounter: "Hiraldo the Swordsman trains in a secluded box canyon" },
      { encounter: "A snorting minotaur emerges through a carved stone arch" },
      { encounter: "A hunting wyvern swoops down the face of the mountain" },
      { encounter: "2d6 hobgoblins form a shield wall against a fat hill giant" },
      { encounter: "A praying knight sits in the cold crash of a narrow waterfall" },
      { encounter: "A shrine to Madeera grants +1 luck token for an offering" },
      { encounter: "A two-headed ogre argues with itself while cooking stew" },
      { encounter: "The Wandering Merchant looks for rare newts under rocks" },
      { encounter: "Rathgamnon the Sphinx flies in to bestow a magic item" }
    ],
    ocean: [
      { encounter: "A massive whirlpool opens up, threatening all ships within" },
      { encounter: "An angry storm giant asks why the PCs are in her realm" },
      { encounter: "A hydra and a kraken churn the seas in their epic struggle" },
      { encounter: "Lyrellos, a merfolk prince, is displeased with the PCs' garb" },
      { encounter: "A rogue wave pelts toward PCs; it's a water elemental" },
      { encounter: "A giant octopus grabs at the PCs from below the water" },
      { encounter: "A whipping storm batters the group and threatens vessels" },
      { encounter: "2d6 sahuagin try to take the characters captive" },
      { encounter: "3d6 pirates on the Crimson Sky try to intercept the PCs" },
      { encounter: "Thick, brown algae turns the water surface into mud" },
      { encounter: "A swarm of giant rats swims away from a shipwreck" },
      { encounter: "A massive plesiosaurus rises from the dark depths" },
      { encounter: "A press gang of pirates appears on a fast, black galley" },
      { encounter: "2d4 sirens sing from a rocky atoll jutting from the sea" },
      { encounter: "A giant octopus and plesiosaurus fight to the death" },
      { encounter: "A ghost and 3d20 skeletons crew a listing, abandoned ship" },
      { encounter: "1d6 sharks circle the PCs and try to upend any vessels" },
      { encounter: "A bone naga slithers along the surface like a sea snake" },
      { encounter: "Treacherous coral reefs hinder the passage of ships" },
      { encounter: "A rolling fog on the water hides 2d4 glowing will-o'-wisps" },
      { encounter: "2d8 merfolk outlaws demand a toll for safe passage" },
      { encounter: "A dehydrated, sun-scorched pirate floats by in a rum barrel" },
      { encounter: "High waves toss droves of violet jellyfish through the air" },
      { encounter: "A ravenous hydra explodes out of the water" },
      { encounter: "2d6 wights approach on a skull-festooned longboat" },
      { encounter: "Beneath a sea volcano, a water and fire elemental battle" },
      { encounter: "A whirling water spout tears across the surface of the sea" },
      { encounter: "A colossal rogue wave lasting 1d4 rounds threatens vessels" },
      { encounter: "A sea hag posing as an injured mermaid begs for help" },
      { encounter: "A floating, white tower houses a distracted archmage (N)" },
      { encounter: "A storm giant pulled by two giant manta rays stops to chat" },
      { encounter: "A school of 2d20 jellyfish descends upon the PCs" },
      { encounter: "2d100 migrating birds rest on any objects above the water" },
      { encounter: "A green bottle with a parchment inside bobs on the waves" },
      { encounter: "1d4 brain eaters approach in a conch-shaped submarine" },
      { encounter: "2d6 sahuagin quietly dart toward 3d10 merfolk peasants" },
      { encounter: "A group of rival crawlers inspect a map aboard the Merlass" },
      { encounter: "A ship on the horizon appears to be floating above the sea" },
      { encounter: "A passing storm cloud rains a piranha swarm onto the PCs" },
      { encounter: "2d6 giant crabs bask on a coral reef dotted with wrecks" },
      { encounter: "Sillenion the sea dragon (L) is curious about 'land-folk'" },
      { encounter: "A barnacle-encrusted giant manta ray drifts into sight" },
      { encounter: "An alabaster stone golem trudges along the sea floor" },
      { encounter: "A storm giant fights a losing battle against a megalodon" },
      { encounter: "A merchant vessel, The Jade Lion, welcomes folk aboard" },
      { encounter: "A rare bloom of scintillating algae can end one curse" },
      { encounter: "3d10 harpies flit around the mouth of a steaming volcano" },
      { encounter: "The Wandering Merchant rows by in a bobbing dinghy" },
      { encounter: "Roll two encounters and combine the results (reroll 98-99)" },
      { encounter: "A seagull flying overhead drops a random magic item" }
    ],
    riverAndCoast: [
      { encounter: "A tsunami overflows the shore, raising it 10' for 2d4 rounds" },
      { encounter: "A clutch of 1d4 basilisks sun themselves on flat rocks" },
      { encounter: "3d6 peasants fearfully inspect a dying giant snake" },
      { encounter: "Mirell, a pearl and gold prospector, yells at 'spot poachers'" },
      { encounter: "3d8 kobolds skim under the surface with reed snorkels" },
      { encounter: "A troll lurks in a damp cave along the water's edge" },
      { encounter: "A 1d4 x 10' wide pit of quicksand or mud opens underfoot" },
      { encounter: "A jumping piranha swarm leaps from the shallows" },
      { encounter: "A sea hag gathers greasy weeds along the water's edge" },
      { encounter: "A poisonous bloom of red algae chokes the shoreline" },
      { encounter: "1d4 holes full of black water turn out to be black puddings" },
      { encounter: "3d8 orcs led by an orc chieftain camp near the water" },
      { encounter: "3d6 river bandits lunge out of hiding on rickety rowboats" },
      { encounter: "A pack of 2d8 hunting lions prowl the shoreline" },
      { encounter: "A hippogriff desperately wrestles a locked-on crocodile" },
      { encounter: "2d6 goblin gem divers operate out of a ramshackle hut" },
      { encounter: "2d4 apes sift through the water for darting minnows" },
      { encounter: "2d4 territorial centaurs spearfish in the shallows" },
      { encounter: "A tidal surge grabs at the PCs, threatening to pull them in" },
      { encounter: "1d4 hippopotami travel with an equal number of calves" },
      { encounter: "A giant crab covered in weeds rears out of the water" },
      { encounter: "Falsted the halfling clings to a sinking, overturned dinghy" },
      { encounter: "Woven reeds or seaweed mask a 20' deep, spear-lined pit" },
      { encounter: "An elephant swims with only its trunk above the surface" },
      { encounter: "1d4 faeries trapped in corked glass bottles float by" },
      { encounter: "2d6 lizardfolk circle in around a flailing giant crab" },
      { encounter: "A weighted and barbed net launches out of the silt or sand" },
      { encounter: "A gladiator with a helm stuck on backwards gropes along" },
      { encounter: "A pride of 2d4 griffons roosts on high rocks or in trees" },
      { encounter: "3d6 peasants live in colorful tents on lashed-together rafts" },
      { encounter: "Yggral the treant stands on the shore, staring at the sky" },
      { encounter: "A circle of 2d4 crooked statues turn out to be gargoyles" },
      { encounter: "1d4 old rowboats are tied to a battered, rotting dock" },
      { encounter: "2d6 giant leeches try to bite warm-blooded swimmers" },
      { encounter: "Thin tunnels in the mud or sand house a snake swarm" },
      { encounter: "3d6 frenzied mastiffs won't let an exhausted elf ashore" },
      { encounter: "A group of rival crawlers portage an overladen canoe" },
      { encounter: "An unlit lighthouse stands on a narrow, sandy island" },
      { encounter: "2d4 stingbats buzz along the surface of the water" },
      { encounter: "Silver Sea, a massive galleon, has run deeply aground" },
      { encounter: "Marga the Wise forages for curative crystals and plants" },
      { encounter: "A herd of 3d6 wild horses thunders up the shoreline" },
      { encounter: "The kobold sorcerer Mortimus preaches from atop a log" },
      { encounter: "2d4 cultists fight 2d6 lizardfolk around a carved obelisk" },
      { encounter: "Quargot the fisherman welcomes peaceful folk to his hut" },
      { encounter: "2d8 opaline shellfish cluster in tide pools; they have pearls" },
      { encounter: "3d8 giant frogs croak one-word insults in Common" },
      { encounter: "The Wandering Merchant walks in the shallows on stilts" },
      { encounter: "Roll two encounters and combine the results (reroll 98-99)" },
      { encounter: "A half-buried treasure chest contains a magic item" }
    ],
    slums: [
      { encounter: "3d8 Bywater Barons (thugs) pour out of a dark tenement" },
      { encounter: "A press gang of 2d4 bandits tries to kidnap the PCs" },
      { encounter: "2d6 thugs surround two greenhorn City Watch guards" },
      { encounter: "A pox-ridden man clutches at the PCs, begging for food" },
      { encounter: "1d6 giant centipedes writhe out of a midden heap" },
      { encounter: "A pack of 2d4 rabid mastiffs begins stalking the group" },
      { encounter: "A burning shop groans and collapses into the street" },
      { encounter: "2d4 commoners clamor to get the butcher's offal scraps" },
      { encounter: "A dark shape (a hunting ghoul) slips along a rooftop" },
      { encounter: "1d4 cloaked chaos cultists slip into an abandoned temple" },
      { encounter: "1d4 giant dung beetles skitter up the side of a tavern" },
      { encounter: "2d4 thugs demand a toll; they let the PCs pass if paid" },
      { encounter: "3d6 nervous City Watch march toward the Bilge Pot tavern" },
      { encounter: "A dying man in a gutter begs to impart a dire secret" },
      { encounter: "2d4 street goons fight with bottle shards and clubs" },
      { encounter: "A dead body falls from a roof with a note: 'Bywater scum'" },
      { encounter: "Residents cluster outside a tenement; screams echo inside" },
      { encounter: "A frantic, manacled man wriggles out of a cellar window" },
      { encounter: "A mob of begging children grows the more the PCs give" },
      { encounter: "Woeful Friar Hector rushes to the summons for last rites" },
      { encounter: "A towering thug bars the PCs' way: 'Find another route'" },
      { encounter: "A rangy crone sells 'love potions' (polymorph to newt)" },
      { encounter: "A snapped clothesline falls, entangling a character" },
      { encounter: "A body in an alley bears a note: 'Pay in coin, or blood. -B.B.'" },
      { encounter: "1d4 people chase a pig barreling through all obstacles" },
      { encounter: "3d4 Bywater Barons (thugs) tell the PCs to leave, 'or else'" },
      { encounter: "1d4 children lure a giant dung beetle into a large cage" },
      { encounter: "A dour mage and 1d4 apprentices lead a tense commoner" },
      { encounter: "A halfling at the well glances around and uncorks a vial" },
      { encounter: "Chanting emanates from an old, crumbling temple" },
      { encounter: "A young noble in spotless 'lowborn rags' fails to blend in" },
      { encounter: "1d4 rabid, screeching rats spring from a midden pile" },
      { encounter: "A back-alley statue of Shune holds out stained hands" },
      { encounter: "A gaunt man sidles up and whispers, 'Bloodroot, 3 silver'" },
      { encounter: "Workers lifting heavy crates slip; one gets trapped beneath" },
      { encounter: "A cheerful street peddler sells crispy rat-on-a-stick for 2 cp" },
      { encounter: "A rival crawling group warily prods at a bricked-up door" },
      { encounter: "Distant sobbing (a ghost) rises from a boarded-up building" },
      { encounter: "Crazy Davord challenges a PC to a game of 'drop the boot'" },
      { encounter: "A grim team of 2d4 bounty hunters (soldiers) eye the PCs" },
      { encounter: "A goblin mage lurking on a roof offers a spell for a favor" },
      { encounter: "1d6 silent workers are actually zombies serving a sorcerer" },
      { encounter: "'Harmless' Uncle Istvold stalks the PCs while cackling" },
      { encounter: "A raging berserker stumbles out of a drug house" },
      { encounter: "A bent, old woman offers safe shelter inside from ruffians" },
      { encounter: "A loose flagstone conceals a box with 80 gp and a potion" },
      { encounter: "1d6 thugs throw bricks through a shop's windows" },
      { encounter: "The Wandering Merchant pays 5 gp per giant dung beetle" },
      { encounter: "Roll two encounters and combine the results (reroll 98-99)" },
      { encounter: "A soiled parchment flutters to the ground; it's a spell scroll" }
    ],
    swamp: [
      { encounter: "A 3x mutated otyugh rises out of the muck" },
      { encounter: "Thorash the swamp dragon (C) lurks in shallow water" },
      { encounter: "2d4 giant frogs leap and snap at a cloud of 3d6 stingbats" },
      { encounter: "Grizella Mosspeat, a night hag, poles along on a rotting raft" },
      { encounter: "An undead T-Rex stomps around, shaking the swamp" },
      { encounter: "2d8 well-preserved zombies stand up out of a peat bog" },
      { encounter: "Dense mud gives way into a slushy field of quicksand" },
      { encounter: "2d6 mottled lizardfolk approach the PCs in an ambush" },
      { encounter: "A gnoll tied to the trunk of a wide tree begs for release" },
      { encounter: "A cloud of mosquitoes whines, bites, and obscures vision" },
      { encounter: "2d4 gnolls patrol through the swamp around their territory" },
      { encounter: "2d6 filthy, long-haired apes hurl rocks from the mangroves" },
      { encounter: "2d6 peasants with torches and pitchforks chase a werewolf" },
      { encounter: "1d4 gargoyles watch from the tops of pitted, leaning pillars" },
      { encounter: "2d6 lizardfolk leap from the mud to attack 2d4 elves" },
      { encounter: "A headless scarecrow stands on a rock holding a lit lantern" },
      { encounter: "A basilisk hisses from inside a pitch-dark, damp cave" },
      { encounter: "1d8 giant leeches fall onto the PCs from wet tree branches" },
      { encounter: "Dense patches of stinging nettles and toxic thorns grow" },
      { encounter: "A fast-moving swarm of snakes slithers along the ground" },
      { encounter: "2d6 giant rats leer from inside rotting logs and tree trunks" },
      { encounter: "Sir Augrim, a knight, is stuck up to his neck in quicksand" },
      { encounter: "A yellow haze of poisonous swamp gas drifts over the bog" },
      { encounter: "3d6 mushroomfolk tend to trees bursting with dewy fungi" },
      { encounter: "The naga Coagulus Mortus sits atop a heap of rotten bones" },
      { encounter: "1d4 ogres lumber by, arguing about what elves taste like" },
      { encounter: "3d6 patches of burning oil float and drift on the water" },
      { encounter: "1d6 giant spiders creep through the dense treetops" },
      { encounter: "2d4 cockatrices sit on their eggs inside a vine-draped cave" },
      { encounter: "A shattered, leaning keep houses a muttering ghost" },
      { encounter: "Blugbort, goblin wizard (N), hunts for slugs and toadstools" },
      { encounter: "1d4 ghasts lead a group of 2d6 zombies and 2d8 skeletons" },
      { encounter: "A cloud of crows darts around a crumbling, ancient well" },
      { encounter: "3d10 goblins drag a rotund hill giant on a makeshift sled" },
      { encounter: "3d6 elves watch the PCs from hiding, deciding if to attack" },
      { encounter: "A grick drags a riderless, kicking horse into a black pond" },
      { encounter: "A group of rival crawlers prods at a half-sunken menhir" },
      { encounter: "A giant snake plunges out of a muddy hole in the ground" },
      { encounter: "A fire-eyed wight rides by on a nightmare trailing flames" },
      { encounter: "What appears to be a filmy puddle is actually a gray ooze" },
      { encounter: "Ol' Greenguts the giant frog helps with the PCs' next task" },
      { encounter: "An orc chieftain leads 3d12 Snake Fang orcs on a rampage" },
      { encounter: "Gorgoth, a priest of Shune (C), whispers to a black obelisk" },
      { encounter: "1d4 muddy hippos thrash and gore 1d6 hissing crocodiles" },
      { encounter: "The Yellow Snail kobolds (2d20) live peacefully in tree huts" },
      { encounter: "Bubbling swamp tar has healing and anti-toxin properties" },
      { encounter: "1d4 shambling mounds trudge through the slimy muck" },
      { encounter: "The Wandering Merchant rides on an albino crocodile" },
      { encounter: "Roll two encounters and combine the results (reroll 98-99)" },
      { encounter: "The Swamp Shambler (gorilla) offers a random magic item" }
    ],
    tavern: [
      { encounter: "A cloaked man (vampire) at the door asks to be invited in" },
      { encounter: "2d6 Overlord's Assassins sweep in and scan the crowd" },
      { encounter: "3d6 patrons watching a tense dice game erupt in a brawl" },
      { encounter: "2d6 boorish sailors swarm in and hog the entire bar area" },
      { encounter: "A sour-faced patron buys a drink for everyone but the PCs" },
      { encounter: "A PC is mistakenly announced as the next pit fighter" },
      { encounter: "A drunk halfling swings on an ancient, creaking chandelier" },
      { encounter: "A woman stalks up and throws a drink in a PC's face" },
      { encounter: "A patron's raw cobra order rears up from the plate, hissing" },
      { encounter: "A slippery puddle of foamy ale spreads over the floor" },
      { encounter: "A half-orc roars and lifts a full-sized table over his head" },
      { encounter: "A long, terrified scream comes from the kitchen" },
      { encounter: "A group of rival crawlers tell the PCs this is their tavern" },
      { encounter: "A slender man whispers, 'Need poison? Best you can buy!'" },
      { encounter: "A smirking elf challenges a PC to dice; the dice are loaded" },
      { encounter: "A dour mage studies a book and glares at noisemakers" },
      { encounter: "A half-orc and halfling arm wrestle; the halfling is winning" },
      { encounter: "Two rival bards start an uproarious singing contest" },
      { encounter: "A sailor throws another onto the PCs' table, spilling drinks" },
      { encounter: "Five merry dwarves sing a shanty and headbutt each other" },
      { encounter: "1d6 patrons (chaos cultists) skulk into the back room" },
      { encounter: "An enraged, sprinting crocodile bursts out of the kitchen" },
      { encounter: "A hooded patron smashes a flask of flaming oil and runs" },
      { encounter: "A dwarf in clogs challenges a PC to a dancing contest" },
      { encounter: "Atticus Gnarl, a halfling wizard, stares unblinking at a PC" },
      { encounter: "Rival crawlers challenge the PCs to a drinking contest" },
      { encounter: "A halfling tries to stealthily tie the PCs' bootlaces together" },
      { encounter: "A man grabs a PC and shouts, 'You know what you did!'" },
      { encounter: "Drunk dart throwers can hardly tell which way is up" },
      { encounter: "A woman flawlessly lifts a coin purse from a patron's belt" },
      { encounter: "Rival crawlers whisper over a book and point to passages" },
      { encounter: "2d6 City Watch guards tromp wearily through the door" },
      { encounter: "A landscape painting subtly changes when not observed" },
      { encounter: "A half-orc gulps a whole flagon and punches the server" },
      { encounter: "A woman in dark-blue leathers sips tea and observes" },
      { encounter: "A cloaked figure jumps the bar and goes for the coin box" },
      { encounter: "Rival crawlers try to pawn off a map nobody can decipher" },
      { encounter: "Everyone avoids the chained trapdoor of stone in the floor" },
      { encounter: "Four whispering commoners stop and glare at passersby" },
      { encounter: "A woman picks up a chair and smashes it on a man's head" },
      { encounter: "A sympathetic City Watch guard shares an inside rumor" },
      { encounter: "Violet Dorn, a widely renowned bard, walks into the tavern" },
      { encounter: "A weeping priest wobbles over and collapses on a PC" },
      { encounter: "At the sound of a nearby Watch whistle, 1d6 patrons bolt" },
      { encounter: "A well-heeled patron invites the PCs into a private booth" },
      { encounter: "The brass wolf's nose imparts good luck (5% for luck token)" },
      { encounter: "A patron slips a note to a PC: 'You're surrounded by spies'" },
      { encounter: "The Wandering Merchant has a Van Dinkle flask (pg. 137)" },
      { encounter: "Roll two encounters and combine the results (reroll 98-99)" },
      { encounter: "A die sits in a dusty corner; it's Brak's Cube of Perfection" }
    ],
    templeDistrict: [
      { encounter: "2d6 chaos cultists begin a live sacrifice; it's a beloved NPC" },
      { encounter: "A routine exorcism expels a very non-routine erinyes" },
      { encounter: "An old man dumps a stream of gems into an alms box" },
      { encounter: "A stampede of religious pilgrims rushes down the street" },
      { encounter: "A crowd clamors to touch a holy relic carried on a platform" },
      { encounter: "A priest screams, 'It's all a lie!' and turns into a bone naga" },
      { encounter: "A roof cistern collapses; water and stone crash down" },
      { encounter: "Three acolytes accuse the PCs of treading on a holy tomb" },
      { encounter: "Lashing tentacles erupt from the sleeves of a chaos cultist" },
      { encounter: "Frenzied Bloodletting celebrants crack whips at passersby" },
      { encounter: "Penitents in chains carry a litter bearing a high priest" },
      { encounter: "A cowled person leaves a basket at a chapel; it's an infant" },
      { encounter: "2d4 blindfolded pilgrims sit in a circle and block the street" },
      { encounter: "Two beggars conceal wavy daggers up their sleeves" },
      { encounter: "A man falls down in rapture and turns into a fire elemental" },
      { encounter: "Movement darts inside the boarded-up ruins of a church" },
      { encounter: "A priestess storms from a temple, flinging her holy symbol" },
      { encounter: "Whispering chaos cultists gather at a back-alley shrine" },
      { encounter: "A trapdoor in an alley falls open to the cellar of a temple" },
      { encounter: "1d6 skulking acolytes hunt for a lone beggar to kidnap" },
      { encounter: "A red-mouthed man says a new church has free bloodroot" },
      { encounter: "1d4 knights hold a public inquisition for an accused witch" },
      { encounter: "The Holy Bull Run commences with screams and gorings" },
      { encounter: "Four masked thugs disrupt an opulent funeral procession" },
      { encounter: "A man leaps up and shouts, 'I object!' during a wedding" },
      { encounter: "A poxed beggar wanders around in a feverish delirium" },
      { encounter: "Mystics burn hallucinogenic incense in the street" },
      { encounter: "2d4 bandits pose as monks collecting alms for the poor" },
      { encounter: "A cultist in the shadows throws a poisoned dart at a PC" },
      { encounter: "A firebrand orator preaches to a growingly frenzied crowd" },
      { encounter: "A commoner's eyes turn white and she utters an augury" },
      { encounter: "Debauched cultists of Gede hand out endless cups of wine" },
      { encounter: "A priest with a forced smile offers 5 gp to new converts" },
      { encounter: "2d6 acolytes clash over a difference in text interpretation" },
      { encounter: "The Parade of the Nine draws onlookers and pickpockets" },
      { encounter: "A monk lights himself on fire and walks into a temple" },
      { encounter: "A rival group of crawlers exit a church, freshly baptized" },
      { encounter: "The City Watch drags flailing Baron Hallin out of a temple" },
      { encounter: "Mystics hold up cobras to be kissed; 10% of cobras lash out" },
      { encounter: "A priest flings holy water from a brush; it burns the chaotic" },
      { encounter: "A templar disguised as a commoner tends to a fallen leper" },
      { encounter: "A woman screams, 'All will dissolve!' and throws acid" },
      { encounter: "1d6 City Watch try to subdue a man in a violent rapture" },
      { encounter: "A domini angel appears in a burst of light; it points to a PC" },
      { encounter: "A temple of St. Terragnis offers sanctuary to the unarmed" },
      { encounter: "The Font of Madeera has a 5% chance of ending a curse" },
      { encounter: "The Overlord enters a temple surrounded by 3d6 knights" },
      { encounter: "The Wandering Merchant sells lookalike priest's vestments" },
      { encounter: "Roll two encounters and combine the results (reroll 98-99)" },
      { encounter: "A high priest selects a PC to receive a rare blessing" }
    ],
    tomb: [
      { encounter: "A distracted, muttering lich teleports into the room" },
      { encounter: "2d4 wraiths emerge from walls, floors, and ceilings" },
      { encounter: "2d6 ghasts claw and thrash around inside a swarm of bats" },
      { encounter: "Muggins Greenbottle, halfling tomb robber, was here first" },
      { encounter: "2d4 wererats in human form paw through piles of rubble" },
      { encounter: "A scarab swarm boils out of cracks in the floors and walls" },
      { encounter: "Necrotic energy turns a near-sized area dangerously cold" },
      { encounter: "1d6 malodorous rot flowers burst through weakened stone" },
      { encounter: "1d4 spiders descend onto the backs of necks" },
      { encounter: "The Sphere of Annihilation glides along, moving randomly" },
      { encounter: "A wight leads a shambling patrol of 3d12 skeletons" },
      { encounter: "A pile of thin, long bones assembles into a bone naga" },
      { encounter: "3d6 confused peasants have awoken from a magical stasis" },
      { encounter: "1d4 mummies lope around, moaning in ancient Common" },
      { encounter: "A gelatinous cube contains 2d6 skeletons trying to escape" },
      { encounter: "An angry ghost must stay within near of its own remains" },
      { encounter: "2d4 shadows try to sneak up on the PCs from behind" },
      { encounter: "A group of 2d4 superstitious, jumpy orcs hunts for loot" },
      { encounter: "A screaming wind of spirits robs all unused luck tokens" },
      { encounter: "An oni demands to know where its stolen sword is hidden" },
      { encounter: "1d6 corroded animated armors pursue 1d4 rust monsters" },
      { encounter: "The soul of Hirael the elf is trapped inside a musty painting" },
      { encounter: "A 20' patch of shadowy darkness extinguishes all light" },
      { encounter: "A wraith and 1d4 shadows hover around a dark floor crack" },
      { encounter: "2d6 thieves leap out and demand the PCs' plunder" },
      { encounter: "3d8 zombies fight each other to eat a surrounded bandit" },
      { encounter: "A jackal carving drains 1d6 HP/round to all within near" },
      { encounter: "2d4 ghouls tear through the walls where they were buried" },
      { encounter: "A cave creeper devours a freshly destroyed zombie" },
      { encounter: "2d6 zombies endlessly pile the same bricks into new cairns" },
      { encounter: "A vampire offers safe passage in exchange for sips of blood" },
      { encounter: "2d4 demon-faced gargoyles flap up the halls, howling" },
      { encounter: "A skull rolls around, stopping to give critique or comment" },
      { encounter: "A black ooze drips down from thin cracks in the ceiling" },
      { encounter: "2d6 cultists steal along looking for unholy relics to claim" },
      { encounter: "1d4 wraiths chase the terrified ghost of a human peasant" },
      { encounter: "1d6 rival crawlers flee from their own hostile shadows" },
      { encounter: "A cloud of blood boils through; it whispers quiet secrets" },
      { encounter: "A slavering ghoul is pinned to the wall by four iron spikes" },
      { encounter: "3d6 swaying zombies lurch along in a mindless horde" },
      { encounter: "A seraph lays a blessing on the remains of a holy knight" },
      { encounter: "2d4 chanting acolytes (C) lead a blood-anointed reaver" },
      { encounter: "An urn that says 'Bimbles' holds a blue zombie cockatrice" },
      { encounter: "A centipede swarm overruns a thrashing cave creeper" },
      { encounter: "A radiant wight (L) animated by holy energy approaches" },
      { encounter: "A soft bell chimes; all who listen for 2 rounds heal 2d6 HP" },
      { encounter: "The human archmage Rantarim (N) hunts for an old tome" },
      { encounter: "The Wandering Merchant pops, gasping, out of a coffin" },
      { encounter: "Roll two encounters and combine the results (reroll 98-99)" },
      { encounter: "A secret cache holds 1d4 items from the 7-9 treasure table" }
    ],
    universityDistrict: [
      { encounter: "A drunk apprentice wizard summons a furious marilith" },
      { encounter: "Grabbing tentacles erupt through a sewer grate" },
      { encounter: "Two professors' long feud boils over into spell-slinging" },
      { encounter: "A woman furtively offers to pay for 'recently dead bodies'" },
      { encounter: "A hit man jumps on stage where a philosopher speaks" },
      { encounter: "A teenager carrying a grimoire flees from a bookstore" },
      { encounter: "The sky rains yellow acid; a spell has gone very wrong" },
      { encounter: "An old tinker sells one-use confetti bombs and sparklers" },
      { encounter: "A cloud of 2d4 purple stingbats gout from a chimney" },
      { encounter: "City guards frantically cordon off a wide circle of blue fire" },
      { encounter: "A shifty man sells 'cheap potions' (all are 2 mixed potions)" },
      { encounter: "A nearsighted professor insists a PC has an overdue paper" },
      { encounter: "Four bratty students flick copper pieces at people's heads" },
      { encounter: "Tavern-goers flee from a red light inside the Flying Snail" },
      { encounter: "Inhuman howling rises from one of the nearby apartments" },
      { encounter: "The school's wyvern statue, Old Rolf, animates in a frenzy" },
      { encounter: "A red-faced young noble tells a PC to 'show proper regard'" },
      { encounter: "The school's Wizards & Thieves champion challenges a PC" },
      { encounter: "Burning ash rains down from a blown-out tower window" },
      { encounter: "A spectacled mage begins measuring and prodding a PC" },
      { encounter: "A magic cauldron appears, disgorging 1d6 giant rats" },
      { encounter: "A pale man locks eyes with a PC and mouths: 'Help me!'" },
      { encounter: "A PC steps on a prank rune that glues their shoes down" },
      { encounter: "Two animated armor suits duel destructively in the street" },
      { encounter: "A meek student being grilled by a guard points to the PCs" },
      { encounter: "2d6 kobolds swarm from the sewers to steal bags" },
      { encounter: "A practicing wizard targets a PC with a charm person spell" },
      { encounter: "1d4 gargoyles swoop down from a facade to grab a PC" },
      { encounter: "Four thugs stalk the alleys, looking for an easy mark to rob" },
      { encounter: "A witch is telling fortunes from a makeshift stall for 1 gp" },
      { encounter: "A student asks to apprentice with one of the PCs" },
      { encounter: "A sorcerer (oni in disguise) drinks and watches the group" },
      { encounter: "An animated owl statue surreptitiously follows the PCs" },
      { encounter: "A mage tries to pull a PC into an alley to siphon off blood" },
      { encounter: "Crashing and bellowing erupts inside a library" },
      { encounter: "A spellbook flaps out of a window and tries to escape" },
      { encounter: "A professor summons a vrock but loses control of it" },
      { encounter: "Three loan collectors (thugs) surround a hapless student" },
      { encounter: "A wizard's pet cockatrice gets free inside a packed tavern" },
      { encounter: "Three overconfident apprentices pick a fight with the PCs" },
      { encounter: "An artist stops a PC and pleads to draw a charcoal portrait" },
      { encounter: "A nervous librarian hands a PC a strange book and flees" },
      { encounter: "Professor Krall snaps, leading 2d6 zombies into the streets" },
      { encounter: "Students from a rival university vandalize a revered statue" },
      { encounter: "A scholar offers a ruby as a prize for answering a riddle" },
      { encounter: "A clumsy wizard breaks a glass bottle housing a naga" },
      { encounter: "The PCs stumble into an occult ritual with 5 apprentices" },
      { encounter: "The Wandering Merchant sells caustic alchemical reagents" },
      { encounter: "Roll two encounters and combine the results (reroll 98-99)" },
      { encounter: "An archmage entrusts a random magic item to the PCs" }
    ]
  };
  